lastupdatecheck: 0
recentrepos:
    - /home/jeroen/.termieter
    - /home/jeroen/Work/jackjoe/justified
startuppopupversion: 5
didshowhunkstaginghint: false
lastversion: 0.56.0
customcommandshistory: []
hidecommandlog: false
